project:
  type: website
  output-dir: docs
website:
  sidebar:
    
    background: secondary
    search: False
    style: "floating"
    contents: auto
jupyter: python3
format:
  html:
    code-fold: true
    theme: lux
    css: styles.css
    toc: true
    html-math-method: katex
   
execute:
  freeze: auto
  


